Trabajar mediante la librería NumPy sobre los datos de la librería sklearn.datasets descargando el conjunto de datos con nombre "Iris". Este conjunto de datos contiene arrays y listas.

## Ejercicio 1:

Cargar "data" y "target" del conjunto de datos, visualizando los 10 primeros registros de cada uno. Nota: el enunciado original decía "feature", en lugar de "target".

In [1]:
from sklearn import datasets   # Importing sklearn "completely" does not work (to save memory, etc.).
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
type(iris)   # Este objeto de tipo "bunch" viene del paquete scikit-learn (i.e. sklearn).
# Según artículos leídos online, a la práctica se comporta parecido a un diccionario.

sklearn.utils._bunch.Bunch

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [6]:
data = iris['data']

In [7]:
target = iris['target']

Primeros diez elementos de "data":

In [8]:
data[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

Primeros diez elementos de "target":

In [9]:
target[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Ejercicio 2:

Concatenar "data" y "target" en un nuevo array, y mostrar los 5 primeros registros. Si queremos concatenarlas, necesitamos que las dimensiones concuerden.

In [10]:
len(data)

150

In [11]:
data.shape  # Son 150 filas que contienen sub-arrays de 4 elementos.

(150, 4)

In [12]:
len(target)  

150

In [13]:
target.shape  # 150 filas con elementos individuales.

(150,)

Podemos "apilarlas" en la dimensión de las filas, con un "column stack", que implica un "apilamiento horizontal". En otras palabras, como tenemos 150 filas en ambos arrays, podemos combinarlos a nivel de filas.

In [14]:
horizontal_stack = np.column_stack((data,target))

In [15]:
horizontal_stack

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

## Ejercicio 3:

Calcular la media y desviación estándar de la longitud del sépalo (("sepal length (cm)") y la longitud del pétalo ("petal length (cm)"). Mostrar los resultados con dos decimales.

In [19]:
media_long_sepalo = np.mean(horizontal_stack[:,0])

In [25]:
print("Longitud media del sépalo: " + "{:.2f}".format(media_long_sepalo))

Longitud media del sépalo: 5.84


In [23]:
desv_long_sepalo = np.std(horizontal_stack[:,0])

In [24]:
print("Desviación estándar del sépalo: " + "{:.2f}".format(desv_long_sepalo))

Desviación estándar del sépalo: 0.83


In [26]:
media_long_petalo = np.mean(horizontal_stack[:,2])

In [27]:
print("Longitud media del sépalo: " + "{:.2f}".format(media_long_petalo))

Longitud media del sépalo: 3.76


In [29]:
desv_long_petalo = np.std(horizontal_stack[:,2])

In [30]:
print("Desviación estándar del sépalo: " + "{:.2f}".format(desv_long_petalo))

Desviación estándar del sépalo: 1.76


## Ejercicio 4:

Seleccionar una muestra aleatoria de 20 registros del conjunto obtenido en el ejercicio anterior.
Nota: entiendo que se refiere al ejercicio 2, y no al 3.

Lo hacemos siguiendo la documentación de numpy.random.Generator.choice, que se halla en:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html

In [80]:
rng = np.random.default_rng()  # Esto es un objeto generador de números aleatorios.

In [81]:
type(rng)

numpy.random._generator.Generator

In [82]:
muestra_aleatoria = rng.choice(horizontal_stack, 20, replace=False)  
# Especificamos el array del que queremos muestras aleatorias, cuántas queremos, e indicamos que no se pueden repetir.

In [83]:
muestra_aleatoria

array([[5.9, 3.2, 4.8, 1.8, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.8, 2.8, 5.1, 2.4, 2. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6. , 3. , 4.8, 1.8, 2. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [5.7, 2.6, 3.5, 1. , 1. ],
       [6.7, 2.5, 5.8, 1.8, 2. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [6.4, 3.2, 4.5, 1.5, 1. ]])

## Ejercicio 5:

Crear una matriz que muestre:
* La media de cada característica por especie.
* La desviación estándar de cada característica por especie.

In [84]:
# Hemos de tener en cuenta el número de "target" que corresponde a cada especie.
iris['target_names']   # La numeración es 0 = 'setosa'; 1 = 'versicolor'; 2 = 'virginica'

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [85]:
# Creamos dos listas a las que añadiremos lo que nos pide el enunciado.
medias_y_desviaciones = list()

In [86]:
for i in range(0,3):  # Range de 0 a 3, así cubrimos las tres especies, numeradas como cero, uno y dos.
    # Seleccionamos del array de origen "horizontal_stack" aquellas filas que corresponden a la especie "i".
    # De esos registros, hacemos la media de cada columna de interés (por lo tanto usamos "axis=0").
    medias_y_desviaciones.append(horizontal_stack[horizontal_stack[:,4] == i].mean(axis = 0))

for i in range(0,3):
    # Y lo mismo, para la desviación estándar con la función std().
    medias_y_desviaciones.append(horizontal_stack[horizontal_stack[:,4] == i].std(axis = 0))

In [87]:
# Ya tenemos una matriz con, primero las medias, y luego las desviaciones.
medias_y_desviaciones

[array([5.006, 3.428, 1.462, 0.246, 0.   ]),
 array([5.936, 2.77 , 4.26 , 1.326, 1.   ]),
 array([6.588, 2.974, 5.552, 2.026, 2.   ]),
 array([0.34894699, 0.37525458, 0.17191859, 0.10432641, 0.        ]),
 array([0.51098337, 0.31064449, 0.46518813, 0.19576517, 0.        ]),
 array([0.62948868, 0.31925538, 0.54634787, 0.27188968, 0.        ])]

In [88]:
type(medias_y_desviaciones)

list

In [89]:
matriz = np.array(medias_y_desviaciones)

In [90]:
# Recortamos la última columna por limpieza.
matriz_med_desv = matriz[:,:4]

Aquí tenemos el resultado que nos pedía el enunciado:

In [91]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

## Ejercicio 6:

Calcular la cantidad de muestras por especie. Además, encontrar la especie con el mayor valor medio de la variable "sepal length (cm)".

In [38]:
horizontal_stack

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [67]:
np.bincount(list(horizontal_stack[:,4]))
# Nota: hallo que si no convierto a lista, da este error:
# "TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'"
# np.bincount(horizontal_stack[:,4])
# Asimismo, tratar de convertir a entero da este otro error:
# "TypeError: only size-1 arrays can be converted to Python scalars"
# np.bincount(int(horizontal_stack[:,4]))

array([50, 50, 50], dtype=int64)

El array obtenido va por orden [0, 1, 2], y nos indica que hay 50 muestras de cada especie. Si la lista de este contaje fuese muy larga, podríamos buscar el índice de el o los valores máximos con una función como podría ser por ejemplo argmax().

Se nos pedía también la especie con mayor longitud media de la variable sepal length. Esa variable corresponde a la primera columna de "matriz_med_desv".

In [94]:
# Obtención del valor medio máximo de "sepal length":
max(matriz_med_desv[:3,0])

6.587999999999998

Para localizar dónde está el valor, y por lo tanto saber a qué especie corresponde (línea 0 = setosa, línea 1 = versicoulour, línea 2 = virginica):

In [95]:
np.where(matriz_med_desv==max(matriz_med_desv[:3,0]))

(array([2], dtype=int64), array([0], dtype=int64))

Lo anterior nos dice que el valor que buscamos está en la fila "2" (y columna "0"). Es decir, que la media más alta es de la especie "virginica". Esto concuerda con lo que vemos por inspección visual:

In [97]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

## Ejercicio 7

* Calcular la matriz de correlación entre las variables.

* Filtrar los valores mayores que la media de la longitud de los pétalos y mostrarlos.

* Encontrar la muestra con los pétalos más grandes.

Comenzamos con el cálculo de la matriz de correlación.

In [105]:
matr_corr = np.corrcoef(horizontal_stack[:,:4], rowvar=False)
# Especificamos que no use las filas como variables (que es el comportamiento por defecto), sino las columnas.
# También nos quedamos solo con las columnas que contienen datos, eliminamos la columna "target" (o sea, la última).

In [106]:
matr_corr

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

Recordemos qué era cada variable:

In [43]:
iris['feature_names'] # Este resultado nos dice, por orden, qué es cada fila y columna de la matriz.

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

La correlación más fuerte es entre longitud de pétalo y anchura de pétalo, lo cual en principio suena lógico (0,96). Vemos también correlaciones relevantes entre longitud de sépalo y de pétalo, y entre longitud de sépalo y anchura de pétalo (del orden de 0,8-0,9). Es más sorprendente la escasa correlación entre longitud y anchura de sépalo (e incluso levemente negativa).
En cambio, parece haber una débil correlación negativa (del orden de 0,35-0,4) entre anchura de sépalo y la longitud y la anchura del pétalo, respectivamente.

La segunda parte de este ejercicio nos pide que filtremos y mostremos los valores en función de si son mayores o no a la longitud media total de los pétalos.

In [107]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

In [111]:
horizontal_stack[horizontal_stack[:, 2] > media_long_petalo]   # media_long_petalo viene del ejercicio 3.

array([[7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.2, 2.7, 3.9, 1.4, 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [5.6, 3. , 4.5, 1.5, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [5.8, 2.7, 3.9, 1.2, 1. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [5.4, 3

Se nos pregunta cuál es la especie con los pétalos más grandes.

In [48]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

Dado que no sabemos la forma exacta de la flor, podríamos hacer la siguiente aproximación para responder: considerar la flor una forma geométrica, por ejemplo, un rectángulo con lado alto igual a la longitud de pétalo, y con lado corto igual a la anchura de pétalo.

In [49]:
for i in range(0,3):
    print("Para la especie " + str(i) + " podemos estimar un área promedio de " + str(matriz_med_desv[i][2]*matriz_med_desv[i][3]) + "cm^2.")

Para la especie 0 podemos estimar un área promedio de 0.3596519999999999cm^2.
Para la especie 1 podemos estimar un área promedio de 5.648759999999999cm^2.
Para la especie 2 podemos estimar un área promedio de 11.248351999999999cm^2.


Si damos por válida la premisa de nuestra aproximación, podemos argumentar que la especie "2" (Virginica) es la que tiene pétalos más grandes. O bien, podemos simplemente obtener qué especie tiene los pétalos más largos (y que también es virginica).

## Ejercicio 8

Encontrar la especie con la mayor diferencia entre la longitud media de pétalos y sépalos.

In [51]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

In [113]:
dif_max = 0
especie_dif_max=0

for i in range(0,3):
    if abs(matriz_med_desv[i][0]-matriz_med_desv[i][2]) > dif_max:
        dif_max = matriz_med_desv[i][0]-matriz_med_desv[i][2]
        especie_dif_max = i

print("La expecie con mayor diferencia entre longitud de pétalos y sépalos es la " + str(especie_dif_max) + ".")


La expecie con mayor diferencia entre longitud de pétalos y sépalos es la 0.


Deducimos que la especie con la mayor diferencia entre pétalos y sépalos es la cero ("Setosa").