Trabajar mediante la librería NumPy sobre los datos de la librería sklearn.datasets descargando el conjunto de datos con nombre "Iris". Este conjunto de datos contiene arrays y listas.

## Ejercicio 1:

Cargar "data" y "target" del conjunto de datos, visualizando los 10 primeros registros de cada uno. Nota: el enunciado original decía "feature", en lugar de "target".

In [1]:
from sklearn import datasets   # Importing sklearn "completely" does not work (to save memory, etc.).
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
type(iris)   # Este objeto de tipo "bunch" viene del paquete scikit-learn (i.e. sklearn).
# Según artículos leídos online, a la práctica se comporta parecido a un diccionario.

sklearn.utils._bunch.Bunch

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [6]:
data = iris['data']

In [7]:
target = iris['target']

Primeros diez elementos de "data":

In [8]:
data[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

Primeros diez elementos de "target":

In [9]:
target[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Ejercicio 2:

Concatenar "data" y "target" en un nuevo array, y mostrar los 5 primeros registros.

In [10]:
# No se pueden concatenar de forma directa, porque tienen diferente número de dimensiones.
new_array = np.concatenate((data, target))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Si queremos concatenarlas, necesitamos que las dimensiones concuerden. Vemos que al menos la longitud sí es la misma.


In [ ]:
len(data)


In [11]:
data.shape  # Son 150 filas que contienen sub-arrays de 4 elementos.

(150, 4)

In [12]:
len(target)  

150

In [13]:
target.shape  # 150 filas con elementos individuales.

(150,)

Podemos "apilarlas" en la dimensión de las filas, con un "column stack", que implica un "apilamiento horizontal". En otras palabras, como tenemos 150 filas en ambos arrays, podemos combinarlos a nivel de filas.

In [14]:
horizontal_stack = np.column_stack((data,target))

In [15]:
horizontal_stack

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

## Ejercicio 3:

Calcular la media y desviación estándar de la longitud del sépalo (("sepal length (cm)") y la longitud del pétalo ("petal length (cm)"). Mostrar los resultados con dos decimales.

In [16]:
iris['feature_names']

# Se entiende que "sepal length (cm)" es el primer elemento de cada sub-array contenido en data.
# Asimismo, "petal length (cm) es el tercer elemento de cada sub-array contenido en data"

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [17]:
len(data)    # Esta es la cantidad de elementos que hay en el array "data". Ahora usaremos este dato.

150

In [18]:
sepal_length = np.empty(150)  # Creamos un array vacío unidimensional de 150 elementos.
petal_length = np.empty(150)  # Creamos otro array vacío unidimensional de 150 elementos.
    
for i in range(0,150):       # Tomamos elementos concretos de "data" en sendos arrays con longitud de sépalo y pétalo.
    sepal_length[i] = data[i][0]
    petal_length[i] = data[i][2]

In [19]:
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [20]:
petal_length

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

Media aritmética:

In [21]:
sepal_length.mean()

5.843333333333334

In [22]:
print("{:.2f}".format(sepal_length.mean()))  # Con dos decimales.

5.84


In [23]:
petal_length.mean()

3.7580000000000005

In [24]:
print("{:.2f}".format(petal_length.mean()))  # Con dos decimales.

3.76


Desviación estándar (con dos decimales):

In [25]:
print("{:.2f}".format(np.std(sepal_length)))

0.83


In [26]:
print("{:.2f}".format(np.std(petal_length))) 

1.76


## Ejercicio 4:

Seleccionar una muestra aleatoria de 20 registros del conjunto obtenido en el ejercicio anterior.
Nota: entiendo que se refiere al ejercicio 2, y no al 3.

Lo hacemos siguiendo la documentación de numpy.random.Generator.choice, que se halla en:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html

In [27]:
rng = np.random.default_rng()  # Esto es un objeto generador de números aleatorios.

In [28]:
type(rng)

numpy.random._generator.Generator

In [29]:
muestra_aleatoria = rng.choice(horizontal_stack, 20, replace=False)  
# Especificamos el array del que queremos muestras aleatorias, cuántas queremos, e indicamos que no se pueden repetir.

In [30]:
muestra_aleatoria

array([[5.1, 3.7, 1.5, 0.4, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [5. , 3.5, 1.3, 0.3, 0. ],
       [7.2, 3.6, 6.1, 2.5, 2. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [5.7, 2.5, 5. , 2. , 2. ],
       [5.5, 2.4, 3.7, 1. , 1. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [4.9, 2.5, 4.5, 1.7, 2. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [5. , 2. , 3.5, 1. , 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.9, 2.4, 3.3, 1. , 1. ]])

## Ejercicio 5:

Crear una matriz que muestre:
* La media de cada característica por especie.
* La desviación estándar de cada característica por especie.

In [68]:
# Hemos de tener en cuenta el número de "target" que corresponde a cada especie.
iris['target_names']   # La numeración es 0 = 'setosa'; 1 = 'versicolor'; 2 = 'virginica'

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [31]:
# Creamos dos listas a las que añadiremos lo que nos pide el enunciado.
medias_y_desviaciones = list()

In [32]:
for i in range(0,3):  # Range de 0 a 3, así cubrimos las tres especies, numeradas como cero, uno y dos.
    # Seleccionamos del array de origen "horizontal_stack" aquellas filas que corresponden a la especie "i".
    # De esos registros, hacemos la media de cada columna de interés (por lo tanto usamos "axis=0").
    # Esa media obtenida, la añadimos a la lista "means".
    medias_y_desviaciones.append(horizontal_stack[horizontal_stack[:,4] == i].mean(axis = 0))
    
for i in range(0,3):
    # Y lo mismo, para la lista "standads", pero calculando desviación estándar con la función std().
    medias_y_desviaciones.append(horizontal_stack[horizontal_stack[:,4] == i].std(axis = 0))


In [33]:
# Ya tenemos una matriz con, primero las medias, y luego las desviaciones.
medias_y_desviaciones

[array([5.006, 3.428, 1.462, 0.246, 0.   ]),
 array([5.936, 2.77 , 4.26 , 1.326, 1.   ]),
 array([6.588, 2.974, 5.552, 2.026, 2.   ]),
 array([0.34894699, 0.37525458, 0.17191859, 0.10432641, 0.        ]),
 array([0.51098337, 0.31064449, 0.46518813, 0.19576517, 0.        ]),
 array([0.62948868, 0.31925538, 0.54634787, 0.27188968, 0.        ])]

In [34]:
type(medias_y_desviaciones)

list

In [35]:
matriz = np.array(medias_y_desviaciones)

In [36]:
matriz_med_desv = matriz[:,:4]  # Recortamos la última columna, que tal como estaba no da información coherente.

Aquí tenemos el resultado que nos pedía el enunciado:

In [37]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

## Ejercicio 6:

Calcular la cantidad de muestras por especie. Además, encontrar la especie con el mayor valor medio de la variable "sepal length (cm)".

In [38]:
horizontal_stack

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

Podemos ver que hay cincuenta muestras de cada especie:

In [39]:
for i in range(0,3):   # Vemos el número de registros de la especie "0" (Setosa), la "1" (Versicolour) y la "2" (Virginica)
    print(np.count_nonzero(horizontal_stack[:,4] == i))

50
50
50


De acuerdo al orden que tenían los elementos en el objeto "numpy bunch" llamado "iris", de donde hemos sacado los datos originales, la variable "sepal length (cm)" corresponde a la primera columna.
También corresponde a la primera columna de la matriz que hemos creado en el ejercicio anterior, "medias_y_desviaciones".

In [40]:
matriz_med_desv


array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

De observar la matriz, deducimos que la media más alta es la de la especie "2" (Virginica): 6,588 cm

## Ejercicio 7

* Calcular la matriz de correlación entre las variables.

* Filtrar los valores mayores que la media de la longitud de los pétalos y mostrarlos.

* Encontrar la muestra con los pétalos más grandes.

Comenzamos con el cálculo de la matriz de correlación.

In [41]:
matriz_correlacion = np.corrcoef(matriz_med_desv, rowvar=False)
# Especificamos que no use las filas como variables (que es el comportamiento por defecto), sino las columnas.

In [42]:
matriz_correlacion

array([[1.        , 0.95692961, 0.89862715, 0.80873522],
       [0.95692961, 1.        , 0.73524962, 0.61158953],
       [0.89862715, 0.73524962, 1.        , 0.98284852],
       [0.80873522, 0.61158953, 0.98284852, 1.        ]])

Recordemos qué era cada variable:

In [43]:
iris['feature_names'] # El resultado nos dice, por orden, qué es cada fila y columna de la matriz.


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Vemos en la matriz que la correlación más alta es entre la longitud de pétalo y su anchura.

La segunda parte de este ejercicio nos pide que filtremos y mostremos los valores en función de si son mayores o no a la longitud media de los pétalos.

In [44]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

In [45]:
medias_petalos = matriz_med_desv[0:3,2]
# Usaremos los datos de las primeras tres filas (las medias), y la tercera columna (longitud de pétalo).

In [46]:
medias_petalos

array([1.462, 4.26 , 5.552])

In [47]:
mayores_q_media=[]

for i in range(0,150):
    for j in range(0,3):
        if horizontal_stack[i][4] == j:
            if horizontal_stack[i][2] > medias_petalos[j]:
                print("Este valor de la especie número " + str(j) + " es superior a su media, que es: " + str(medias_petalos[j]) + " cm.")
                print(horizontal_stack[i][2])
        
        

Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.5
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.7
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.5
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.5
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.5
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.6
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.5
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.7
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.5
Este valor de la especie número 0 es superior a su media, que es: 1.4620000000000002 cm.
1.7
Este valor de la especie número 0 es superior a su media, que es: 1.46

Se nos pregunta cuál es la especie con los pétalos más grandes.

In [48]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

Dado que no sabemos la forma exacta de la flor, podríamos hacer la siguiente aproximación para responder: considerar la flor una forma geométrica, por ejemplo, un rectángulo con lado alto igual a la longitud de pétalo, y con lado corto igual a la anchura de pétalo.

In [49]:
for i in range(0,3):
    print("Para la especie " + str(i) + " podemos estimar un área promedio de " + str(matriz_med_desv[i][2]*matriz_med_desv[i][3]) + "cm^2.")

Para la especie 0 podemos estimar un área promedio de 0.3596519999999999cm^2.
Para la especie 1 podemos estimar un área promedio de 5.648759999999999cm^2.
Para la especie 2 podemos estimar un área promedio de 11.248351999999999cm^2.


Si damos por válida la premisa de nuestra aproximación, podemos argumentar que la especie "2" (Virginica) es la que tiene pétalos más grandes. 

## Ejercicio 8

Encontrar la especie con la mayor diferencia entre la longitud media de pétalos y sépalos.

In [51]:
matriz_med_desv

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.936     , 2.77      , 4.26      , 1.326     ],
       [6.588     , 2.974     , 5.552     , 2.026     ],
       [0.34894699, 0.37525458, 0.17191859, 0.10432641],
       [0.51098337, 0.31064449, 0.46518813, 0.19576517],
       [0.62948868, 0.31925538, 0.54634787, 0.27188968]])

In [67]:
dif_max = 0
especie_dif_max=0

for i in range(0,3):
    if (matriz_med_desv[i][0]-matriz_med_desv[i][2]) > dif_max:
        dif_max = matriz_med_desv[i][0]-matriz_med_desv[i][2]
        especie_dif_max = i

print("La expecie con mayor diferencia entre longitud de pétalos y sépalos es la " + str(especie_dif_max) + ".")


La expecie con mayor diferencia entre longitud de pétalos y sépalos es la 0.


In [ ]:
Deducimos que la especie con la mayor diferencia entre pétalos y sépalos es la cero ("Setosa").